/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netbeans.projects;

// Button logic 
// 0 for plus 
// 1 for minus
// 2 for multiply
// 3 for divide


/**
 *
 * @author Varun
 */
public class Calc extends javax.swing.JFrame {

    static int old = 0 , count , n1;
    static String bracket;
   
    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
        setSize(380 , 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        ac = new javax.swing.JButton();
        decimal = new javax.swing.JButton();
        exp = new javax.swing.JButton();
        ans = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        leftBracket = new javax.swing.JButton();
        rightBracket = new javax.swing.JButton();
        sinButton = new javax.swing.JButton();
        cosButton = new javax.swing.JButton();
        tanButton = new javax.swing.JButton();
        shiftButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        squareRootButton = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(tf1);
        tf1.setBounds(10, 10, 340, 90);

        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        getContentPane().add(one);
        one.setBounds(20, 340, 50, 40);

        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        getContentPane().add(two);
        two.setBounds(80, 340, 50, 40);

        plus.setText("+");
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });
        getContentPane().add(plus);
        plus.setBounds(210, 340, 60, 40);

        equal.setText("=");
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });
        getContentPane().add(equal);
        equal.setBounds(290, 400, 50, 40);

        multiply.setText("X");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });
        getContentPane().add(multiply);
        multiply.setBounds(210, 280, 60, 40);

        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        getContentPane().add(three);
        three.setBounds(140, 340, 60, 40);

        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        getContentPane().add(four);
        four.setBounds(20, 280, 50, 40);

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        getContentPane().add(five);
        five.setBounds(80, 280, 50, 40);

        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        getContentPane().add(six);
        six.setBounds(140, 280, 60, 40);

        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        getContentPane().add(seven);
        seven.setBounds(20, 220, 50, 40);

        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        getContentPane().add(eight);
        eight.setBounds(80, 220, 50, 40);

        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        getContentPane().add(nine);
        nine.setBounds(140, 220, 60, 40);

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });
        getContentPane().add(zero);
        zero.setBounds(20, 400, 50, 40);

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });
        getContentPane().add(divide);
        divide.setBounds(280, 280, 60, 40);

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });
        getContentPane().add(minus);
        minus.setBounds(280, 340, 60, 40);

        ac.setText("AC");
        ac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acActionPerformed(evt);
            }
        });
        getContentPane().add(ac);
        ac.setBounds(280, 220, 60, 40);

        decimal.setText(".");
        getContentPane().add(decimal);
        decimal.setBounds(80, 400, 50, 40);

        exp.setText("EXP");
        getContentPane().add(exp);
        exp.setBounds(140, 400, 60, 40);

        ans.setText("Ans");
        getContentPane().add(ans);
        ans.setBounds(210, 400, 60, 40);

        delete.setText("DEL");
        getContentPane().add(delete);
        delete.setBounds(210, 220, 60, 40);

        leftBracket.setText("(");
        leftBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftBracketActionPerformed(evt);
            }
        });
        getContentPane().add(leftBracket);
        leftBracket.setBounds(20, 170, 50, 40);

        rightBracket.setText(")");
        rightBracket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightBracketActionPerformed(evt);
            }
        });
        getContentPane().add(rightBracket);
        rightBracket.setBounds(80, 170, 50, 40);

        sinButton.setText("Sin");
        getContentPane().add(sinButton);
        sinButton.setBounds(140, 170, 60, 40);

        cosButton.setText("Cos");
        getContentPane().add(cosButton);
        cosButton.setBounds(210, 170, 60, 40);

        tanButton.setText("Tan");
        getContentPane().add(tanButton);
        tanButton.setBounds(280, 170, 60, 40);

        shiftButton.setText("Shift");
        getContentPane().add(shiftButton);
        shiftButton.setBounds(20, 120, 110, 40);

        logButton.setText("Log");
        getContentPane().add(logButton);
        logButton.setBounds(140, 120, 90, 40);

        squareRootButton.setText("SQRT");
        getContentPane().add(squareRootButton);
        squareRootButton.setBounds(240, 120, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        
        String s1 = tf1.getText();
        
        tf1.setText((s1)+"1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"2");
    }//GEN-LAST:event_twoActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
        // TODO add your handling code here:
        
        String text = tf1.getText();
        
       StringBuilder brackets = new StringBuilder();

        for (char bracket : text.toCharArray()) {
          if ( bracket == '(' || bracket == ')') {
        brackets.append(bracket);
    }
}
        
        
        old = Integer.parseInt(tf1.getText());
        
        tf1.setText("");
        
        count = 0;
    }//GEN-LAST:event_plusActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
         // TODO add your handling code here:
         n1  = Integer.parseInt(tf1.getText());
         
// Button logic 
// 0 for plus 
// 1 for minus
// 2 for multiply
// 3 for divide
         
         
         switch(count){
             
             case 0 : {
                tf1.setText((old + n1)+"");
                break;
             }
             case 1 :{
                  tf1.setText((old - n1)+"");
                break;
             }
             case 2 :{
                  tf1.setText((old * n1)+"");
                break;
             }
             case 3 :{
                  tf1.setText((old / n1)+"");
                break;
             }
             
             
             
         }
         

    }//GEN-LAST:event_equalActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"3");
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"6");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"9");
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        // TODO add your handling code here:
         String s1 = tf1.getText();
        
        tf1.setText((s1)+"0");
    }//GEN-LAST:event_zeroActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        // TODO add your handling code here:
        old = Integer.parseInt(tf1.getText());
        
        tf1.setText("");
        count = 3;
        
    }//GEN-LAST:event_divideActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        // TODO add your handling code here:
        old = Integer.parseInt(tf1.getText());
        
        tf1.setText("");
        count = 2;
    }//GEN-LAST:event_multiplyActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        // TODO add your handling code here:
        old = Integer.parseInt(tf1.getText());
        
        tf1.setText("");
        count = 1;
    }//GEN-LAST:event_minusActionPerformed

    private void acActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acActionPerformed
        // TODO add your handling code here:
        tf1.setText("");
    }//GEN-LAST:event_acActionPerformed

    private void leftBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftBracketActionPerformed
        // TODO add your handling code here:
       
        String s1 = tf1.getText();
        
        tf1.setText((s1)+"(");

    }//GEN-LAST:event_leftBracketActionPerformed

    private void rightBracketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightBracketActionPerformed
        // TODO add your handling code here:
           String s1 = tf1.getText();
        
        tf1.setText((s1)+")");
    }//GEN-LAST:event_rightBracketActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ac;
    private javax.swing.JButton ans;
    private javax.swing.JButton cosButton;
    private javax.swing.JButton decimal;
    private javax.swing.JButton delete;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton exp;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton leftBracket;
    private javax.swing.JButton logButton;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton plus;
    private javax.swing.JButton rightBracket;
    private javax.swing.JButton seven;
    private javax.swing.JButton shiftButton;
    private javax.swing.JButton sinButton;
    private javax.swing.JButton six;
    private javax.swing.JButton squareRootButton;
    private javax.swing.JButton tanButton;
    private javax.swing.JTextField tf1;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
