/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netbeans.projects;

import java.awt.FileDialog;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.Writer;

/**
 *
 * @author Varun
 */
public class Nodepad extends javax.swing.JFrame {
      
    // global Variables
    private File currentFile = null;
    
    
    /**
     * Creates new form Nodepad
     */
    public Nodepad() {
        initComponents();
        setSize(600, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        nw1 = new javax.swing.JMenuItem();
        op1 = new javax.swing.JMenuItem();
        sv1 = new javax.swing.JMenuItem();
        svs1 = new javax.swing.JMenuItem();
        pst1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        cp1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu3.setText("File");

        nw1.setText("New");
        nw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nw1ActionPerformed(evt);
            }
        });
        jMenu3.add(nw1);

        op1.setText("Open");
        op1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op1ActionPerformed(evt);
            }
        });
        jMenu3.add(op1);

        sv1.setText("Save");
        sv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sv1ActionPerformed(evt);
            }
        });
        jMenu3.add(sv1);

        svs1.setText("Save-As");
        svs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svs1ActionPerformed(evt);
            }
        });
        jMenu3.add(svs1);

        jMenuBar2.add(jMenu3);

        pst1.setText("Edit");
        pst1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pst1ActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Cut");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        pst1.add(jMenuItem5);

        cp1.setText("Copy");
        cp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp1ActionPerformed(evt);
            }
        });
        pst1.add(cp1);

        jMenuItem7.setText("Paste");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        pst1.add(jMenuItem7);

        jMenuBar2.add(pst1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void op1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op1ActionPerformed
         
        try{
            
            ta1.setText("");
            
            FileDialog fd =  new FileDialog(this, "FileOpen" , FileDialog.LOAD);
            
            fd.setSize(200 , 200);
            fd.setVisible(true);
            String dn = fd.getDirectory(); // get directory name(dn)
            String fn = fd.getFile(); // get file name(fn)
            File ff = new File(dn , fn); 
            String path = ff.getPath(); // address
            
            //setting current File to ff;
            currentFile = ff;
            
            // get fileName to currentFile
            this.setTitle(fn);
           
            
            // file input stream 
            FileInputStream fis = new FileInputStream(path);
            
            int x = fis.read();
            
            while(x != -1){
                
                ta1.append((char)x + "");
                x = fis.read();
            }
            fis.close();
            
        }catch(Exception tt){
            System.out.println(tt);
        }
    }//GEN-LAST:event_op1ActionPerformed

    private void sv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sv1ActionPerformed
        // TODO add your handling code here:
        
        try{
           
            
            
            
            if(currentFile == null){
                
            FileDialog fd = new FileDialog(this , "SaveFile" , FileDialog.SAVE);
            
            fd.setSize(200 ,200);
            fd.setVisible(true);
            
            String dn = fd.getDirectory();
            
            String fn = fd.getFile();
            
            File ff = new File(dn , fn);
            
            // set currentFile to ff;
            currentFile = ff;
            
            // set title to fn;
            this.setTitle(fn);
            
            String path  = ff.getPath();
            
            FileOutputStream fos = new FileOutputStream(path);
           
            String data = ta1.getText();
            
            byte b[] = data.getBytes();
            
            fos.write(b);
            fos.close();
            
            }else{
                
                try{
                    Writer fileWriter = new FileWriter(currentFile , true); 
                
                fileWriter.append(ta1.getText());
                
                fileWriter.close();
                }catch(Exception tt){
                    System.out.println(tt);
                }
            }
        }catch(Exception tt){
            System.out.println(tt);
        }
    }//GEN-LAST:event_sv1ActionPerformed

    private void pst1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pst1ActionPerformed
       
        ta1.cut();
    }//GEN-LAST:event_pst1ActionPerformed

    private void cp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp1ActionPerformed
        // TODO add your handling code here:
        ta1.copy();
    }//GEN-LAST:event_cp1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
          // TODO add your handling code here:
         ta1.cut();
         
         
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ta1.paste();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void svs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svs1ActionPerformed
        // TODO add your handling code here:
        
         try{
           
            FileDialog fd = new FileDialog(this , "SaveFileAs" , FileDialog.SAVE);
            
            fd.setSize(200 ,200);
            fd.setVisible(true);
            
            String dn = fd.getDirectory();
            
            String fn = fd.getFile();
            
            File ff = new File(dn , fn);
            
            String path  = ff.getPath();
            
            FileOutputStream fos = new FileOutputStream(path);
           
            String data = ta1.getText();
            
            byte b[] = data.getBytes();
            
            fos.write(b);
            this.setTitle(fn);
            fos.close();
            
        }catch(Exception tt){
            System.out.println(tt);
        }
    }//GEN-LAST:event_svs1ActionPerformed

    private void nw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nw1ActionPerformed
        // TODO add your handling code here:
        
        
        
        this.setTitle("untitled.txt");
    }//GEN-LAST:event_nw1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nodepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nodepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nodepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nodepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nodepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cp1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem nw1;
    private javax.swing.JMenuItem op1;
    private javax.swing.JMenu pst1;
    private javax.swing.JMenuItem sv1;
    private javax.swing.JMenuItem svs1;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
