/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.univ.UI;

import com.univ.DAO.StudentDAO;
import com.univ.DTO.StudentDTO;
import java.util.Vector;

/**
 *
 * @author Varun
 */
public class InsertData extends javax.swing.JFrame {

    /**
     * Creates new form InsertData
     */
    
    int id1;
    
    public InsertData() {
        initComponents();
        setSize(500 ,500);
        StudentDAO dao = new StudentDAO();
        id1 = dao.getID();
        sId.setText(id1+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sAddress = new javax.swing.JTextField();
        sMobile = new javax.swing.JTextField();
        sBranch = new javax.swing.JTextField();
        sUsername = new javax.swing.JTextField();
        sPassword = new javax.swing.JTextField();
        sBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        sId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sIdActionPerformed(evt);
            }
        });
        getContentPane().add(sId);
        sId.setBounds(100, 10, 180, 30);

        jLabel1.setText("StudentID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 20, 70, 20);

        jLabel2.setText("StudentName");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 80, 16);

        sName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNameActionPerformed(evt);
            }
        });
        getContentPane().add(sName);
        sName.setBounds(100, 50, 180, 30);

        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 60, 16);

        jLabel4.setText("Mobile");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 60, 16);

        jLabel5.setText("Branch");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 50, 16);

        jLabel6.setText("UserName");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 210, 60, 16);

        jLabel7.setText("Password");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 250, 80, 16);
        getContentPane().add(sAddress);
        sAddress.setBounds(100, 90, 180, 30);

        sMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sMobileActionPerformed(evt);
            }
        });
        getContentPane().add(sMobile);
        sMobile.setBounds(100, 130, 180, 30);
        getContentPane().add(sBranch);
        sBranch.setBounds(100, 170, 180, 30);

        sUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(sUsername);
        sUsername.setBounds(100, 210, 180, 30);

        sPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(sPassword);
        sPassword.setBounds(100, 250, 180, 30);

        sBtn.setText("Save");
        sBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sBtn);
        sBtn.setBounds(120, 300, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sIdActionPerformed
        // TODO add your handling code here:

        StudentDAO dao = new StudentDAO();

        Vector v2 = dao.GetData(Integer.parseInt(sId.getText()));

        if(!v2.isEmpty()){
            sName.setText((String)v2.get(1));
            sAddress.setText((String)v2.get(2));
            sMobile.setText(v2.get(3)+"");
            sBranch.setText((String) v2.get(4));
            sUsername.setText((String) v2.get(5));
            sPassword.setText((String) v2.get(6));
        }
    }//GEN-LAST:event_sIdActionPerformed

    private void sNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNameActionPerformed

    private void sMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sMobileActionPerformed

    private void sUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sUsernameActionPerformed

    private void sPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sPasswordActionPerformed

    private void sBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBtnActionPerformed
        // TODO add your handling code here:

        StudentDTO dto = new StudentDTO();

        dto.setSid(Integer.parseInt(sId.getText()));
        dto.setSname(sName.getText());
        dto.setSadd(sAddress.getText());
        dto.setMob(Integer.parseInt(sMobile.getText()));
        dto.setBranch(sBranch.getText());
        dto.setUnm(sUsername.getText());
        dto.setPw(sPassword.getText());
        dto.setStatus(0);

        StudentDAO dao = new StudentDAO();
        int x = dao.insert(dto);

        if(x == 1){
            sId.setText("");
            sName.setText("");
            sAddress.setText("");
            sMobile.setText("");
            sBranch.setText("");
            sUsername.setText("");
            sPassword.setText("");

        }

    }//GEN-LAST:event_sBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField sAddress;
    private javax.swing.JTextField sBranch;
    private javax.swing.JButton sBtn;
    private javax.swing.JTextField sId;
    private javax.swing.JTextField sMobile;
    private javax.swing.JTextField sName;
    private javax.swing.JTextField sPassword;
    private javax.swing.JTextField sUsername;
    // End of variables declaration//GEN-END:variables
}
